### ISSUE TITLE
Requesting ability to merge scrapbook.rdf

### ISSUE THREAD

**Issue by balbirthomas** [vctfence/scrapbee#16]
Firstly Thank you very much for picking up where scrapbook left off and creating a very useful alternative. Allowing people to migrate their scrapbook RDF files to scrapbee is a great feature.

At present one can have separate directories one for Scrapbee (with scrapbee.rdf) and another for Scrapbook (scrapbook.rdf). This works perfectly. Scrapbook is dead and the future is Scrapbee. So why bother having separate scrapbook.rdf and scrapbee.rdf. Can it be possible to combine them to a single scrapbee.rdf and a single "data" directory. If so, how ? If not please consider this in a future version?

Also the scrapbee.rdf file, formats all tags in a single line and if this is a very big file, most editors will crash trying to open it, even in read only mode. Is it possible to save it will new lines, tabs and such to make it pretty like scrapbook.rdf. I understand these files should never be edited but never the less it would be nice.

**Comment by vctfence** [comment]
Hi, thanks for discussion, the goal of enable multi-rdfs is to make "books", so that you can have trees for different catalogue, such as "science", "movie", "learning"... and so on, this makes it clear and prevent making a huge tree. If multi-rdfs are not needed, you can use one single rdf such as  scrapbook.rdf, the one scrapbook left over, or make a new one. 

And, I just released a tool named "Node Mover", you can move contents between 2 rdfs, so it's possible to merge multi-rdfs to be one, welcome to version 1.7.0.

**Comment by vctfence** [comment]
Another advantage of multi-rdfs is enabling user have rdfs distribute in different part of their storage, for example, different disk partition, to make more flexibility.

**Comment by j1warren** [comment]
**vctfence**
Could you tell what functions the backend has? Is it only moving and accessing files on filesystem, or does it also access internet?

**Comment by vctfence** [comment]
@j1warren By now, only local file system, to overcome lack about FS of Firefox.
