### ISSUE TITLE
Node Mover Tool: Failure Moving Contents Between Two Book Trees

### ISSUE THREAD

**Issue by touwys** [vctfence/scrapbee#45]
_Scrapbee v2.1.4 • Firefox v82.0.3 • Windows 7_

The Node Mover Tool (NMT) fails to **move** selected node contents between two book trees. The move-process starts, but hangs, and eventually it has to be stopped by closing the browser tab.

The NMT **copy** process, however, completes successfully.

Example of the steps that were followed to invoke the move-error, is shown in the following animated gif:

![Node Mover Tool](https://user-images.githubusercontent.com/65730626/98660059-88d44a00-234d-11eb-9358-4e61794a5867.gif)

**Comment by vctfence** [comment]
I pushed with some improvement, Please try to load the addon from code and have a try.

**Comment by touwys** [comment]
I have not done something like this before:

_1. What is the "code" that you refer to, and where do I find it? 
2. What is the risk involved?_

And, assuming I have been able to run the code correctly:

_1. How should I return to the original settings once the code has been run?
2. How do I ascertain that the code has run without error before I retun to the original settings?_

Thank you.

**Comment by vctfence** [comment]
Hi, it's temporary, you can click remove button or just restart firefox to remove it. The only "risk" is being testing version, please testing it with testing rdfs. Just test it as a temporary new version and report problems.

Don't worry about settings, just export your settings, import when settings somehow removed.

**Comment by touwys** [comment]
Please, you would need to explain steps to be executed to do this in an orderly fashion so as to avoid undue error. 

**Some questions:**

1. I assume by "code" you mean your last commit, too?

2. As part of the steps to be followed, need I uninstall the current version of Scrapbee first, before running the code, and then create a temporay set of RDF's to test? _The order in which the steps to be carried out is important._

3. How do I "run" the "code" i.e which file do I open with "Load Temprary Addon" to run it?

![Scrapbee Load Temporary Addon](https://user-images.githubusercontent.com/65730626/98924280-522d3980-24dd-11eb-9098-6de71b1c843d.gif)

4. It is currently possible to move nodes around to different positions in the Node Trees **in the Sidebar**. I use this facility quite often, especially now that I can no longer deploy the NMT. Could such actions perhaps account for the error, here under discussion, where NMT hangs when moving nodes between trees?

![Scrapbee Sidebar Move Nodes](https://user-images.githubusercontent.com/65730626/98925470-b0a6e780-24de-11eb-9b39-13e216ba3466.gif)

Thank you.

**Comment by vctfence** [comment]
Hi, 
1. Right, code = commit here
2. no need to uninstall, the temporarily loaded addon will just override the current version temporarily, the only problem is that the configuration maybe lost sometimes, so export configuration as a backup.

Try the temporarily loaded addon just like regular version with new features, no other difference. Just keep in mind it's testing version. Test it with testing data or data already backed up.

Usually, you need not reinstall backend program, except new version needed.

Just remove temporary addon or restart anytime when you want to back.

3. You can choose any of the files, when you load addon in about:debugging#/runtime/this-firefox page, see:
https://github.com/vctfence/scrapbee/wiki/Debug

4. That's why I want you load addon from code, I commit/push new code for your problems, these must be tested and confirmed unitl released with new version.

Thanks, let me know if you still have questions.

**Comment by vctfence** [comment]
Hi, I found a new bug may cause failure of moving files, I released new version 2.1.5 as quick fix, please just update to test.

**Comment by touwys** [comment]
> Hi, I found a new bug may cause failure of moving files, I released new version 2.1.5 as quick fix, please update.

Updated to v2.15, tested Node Mover Tool by moving a small number of files between the two trees. Updating to v2.1.5 **FIXED** the issue — Thank you! Please share what the bug was i.e. what caused the issue in the first place? By "quick-fix", did you mean that it needs more work to fix this issue permanently?

(Moving files till needs to be tested with a larger number of files, over a prolonged period of time.)


_**Note:**_ Do we close this issue now, or keep it open for the continuation of the discussion on the issue of running test code i.e. last commit? I propose the latter. If so, how do we move it over to a new issue?

**Comment by vctfence** [comment]
A file moving failure interrupts the nodes moving progress.  This is small change and easy to confirm, can be released in short time, that's why I call it "quick-fix"  differ from major versions. So it's already permanently except redesign.

I'd like to close this now, you can reopen once you meet problem again.
