### ISSUE TITLE
Feature Request ♦ Node Mover Tool:  Keyboard & Mouse Selection Options

### ISSUE THREAD

**Issue by touwys** [vctfence/scrapbee#56]
In addition to the present method of selecting nodes by checking their radio boxes, please provide for the multi-selection of nodes by means of the usual mouse-click + SHIFT, or, mouse-click + CTRL key, for respectively contiguous and unconnected selection of nodes.

**Comment by vctfence** [comment]
CTRL is not needed, because there is already multi-selection. I'v pushed new design of NMT, even single-selection was removed. SHIFT enabled to select node in batch. But that causes some behavior changed, we need to think about the new design carefully.

Please try last commit, then let's discuss in details.

**Comment by touwys** [comment]
OK

**Comment by touwys** [comment]
The changes made to selection behaviour, works well. Thank you.
